services:
  backend:
    build: ./backend
    container_name: a03_backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks: [app-net]

  db:
    image: mongo:6
    container_name: a03_db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks: [app-net]

  frontend:
    image: node:20-alpine
    container_name: a03_front_builder
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm ci || npm i && npm run build && ls -la dist"
    networks: [app-net]

  nginx:
    image: nginx:alpine
    container_name: a03_nginx
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks: [app-net]

volumes:
  mongo-data:

networks:
  app-net:
    driver: bridge

